{
 "title": "Internal Transactions Dashboard",
 "time": { "from": "2021-05-06T10:16:51.449Z", "to": "2021-05-06T11:17:16.702Z" },
 "templating": {
  "list": [
   {
    "name": "Address",
    "label": "Address",
    "query": "select distinct address from transactions"
   }
  ]
 },
 "panels": [
  {
   "title": "Value I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(tx_time,$__interval,0),\n  sum(value) AS \"Total Sent\"\nFROM transactions\nWHERE\n  tx_from = address AND\n  address = '$Address'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(tx_time,$__interval,0),\n  sum(value) AS \"Total Received\"\nFROM transactions\nWHERE\n  tx_to = address AND\n  address = '$Address'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Transactions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(tx_time,$__interval),\n  address AS metric,\n  sum(count(blocknumber)) OVER (PARTITION BY address ORDER BY $__unixEpochGroup(tx_time,$__interval)) AS \"count\"\nFROM transactions\nWHERE\n  $__unixEpochFilter(tx_time) AND\n  address = '$Address'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Gas Usage / Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(tx_time,$__interval),\n  address AS metric,\n  avg(gasused) AS \"gas used\"\nFROM transactions\nWHERE\n  $__unixEpochFilter(tx_time) AND\n  address = '$Address'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(tx_time,$__interval),\n  address AS metric,\n  max(gas) AS \"max gas\"\nFROM transactions\nWHERE\n  $__unixEpochFilter(tx_time) AND\n  address = '$Address'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Mean Gas Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(tx_time,$__interval,0),\n  address AS metric,\n  avg(gasused) AS \"recent gas consumption\"\nFROM transactions\nWHERE\n  $__unixEpochFilter(tx_time) AND\n  address = '$Address'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(tx_time,$__interval,0),\n  address AS metric,\n  max(gas) AS \"gas\"\nFROM transactions\nWHERE\n  $__unixEpochFilter(tx_time) AND\n  address = '$Address'\nGROUP BY 1,2\nORDER BY 1,2"
    },
    { "expression": "($avg/$max) * 100", "type": "math" }
   ]
  }
 ]
}